name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: docker pull kiran14585/fastapi:latest

      - name: Stop and remove existing container
        run: |
          docker stop cicd-pipeline-container || true
          docker rm cicd-pipeline-container || true

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name cicd-pipeline-container kiran14585/fastapi:latest
