name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Test
        run: docker run myapp pytest

      - name: Deploy
        # Add your deployment steps here
        # For example: kubectl apply -f deployment.yaml
