name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull Docker image
        run: sudo docker pull kiran14585/fastapi:latest

      - name: Stop and remove old Docker container
        run: |
          sudo docker stop fastapi-container || true
          sudo docker rm fastapi-container || true

      - name: Run Docker container
        run: sudo docker run -d -p 8000:8000 --name fastapi-container kiran14585/fastapi:latest
