name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  CI_pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t kiran14585/fastapi .
      
    - name: Push to Dockerhub
      run: docker push kiran14585/fastapi:latest

  CD_pipeline:
    runs-on: ubuntu-latest
    needs: CI_pipeline
    steps:
    - name: Pull Docker image
      run: sudo docker pull kiran14585/fastapi:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name cicd-pipeline-container kiran14585/fastapi
