name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fetch Docker Hub credentials
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" > ~/.docker/config.json
          echo "${{ secrets.DOCKER_PASSWORD }}" >> ~/.docker/config.json

      - name: Set up SSH key and add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 34.204.67.5 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Build Docker image
        run: docker build -t my_image_name:latest .

      - name: Connect to EC2 and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ip-172-31-83-134 'bash -s' << 'ENDSSH'
          export DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          export DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}"
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull my_image_name:latest
          docker run -d --name my_container -p 8000:8000 my_image_name:latest
          ENDSSH
