name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Fetch Docker Hub credentials
        run: |
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}"
          export DOCKER_USERNAME DOCKER_PASSWORD

      - name: Connect to EC2 and run commands
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@ip-172-31-83-134 'bash -s' << 'ENDSSH'
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker pull kiran14585/fast-api:1.0.0
          docker run -d --name yourcontainer -p 8000:8000 kiran14585/fast-api:1.0.0
          ENDSSH
