name: Local Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull kiran14585/fast-api:1.0.0

      - name: Run Docker container
        run: docker run -d --name yourcontainer -p 8000:8000 kiran14585/fast-api:1.0.0
