name: CI Pipeline

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t kiran14585/fastapi .

      - name: Push to Dockerhub
        run: docker push kiran14585/fastapi:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            # Pull Docker image
            docker pull kiran14585/fastapi:latest
            
            # Stop and remove existing container if any
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            
            # Run Docker container
            docker run -d --name fastapi-app -p 8000:8000 kiran14585/fastapi:latest
